### ISSUE TITLE
When does it upgrade to 2.0?

### ISSUE THREAD

**Issue by kingreatwill** [dbarkwell/Ocelot.ConfigEditor#1]
When does it upgrade to 2.0?

**Comment by dbarkwell** [comment]
I'll create a 2.0 branch along with Ocelot 2.0 but I think that is still in development.

**Comment by dbarkwell** [comment]
Was just looking through Ocelot closed issues and noticed that 2.0 is now supported. I will port it over.

**Comment by dbarkwell** [comment]
current version is running .NET 2.0.

**Comment by kingreatwill** [comment]
Thank you very much!
