### ISSUE TITLE
How to access the edit

### ISSUE THREAD

**Issue by wangxin5355** [dbarkwell/Ocelot.ConfigEditor#8]
I have test example ,but how to get in the edit page.
if I want access  in with no Authentication ，how to make it

**Comment by dbarkwell** [comment]
From the example:

.ConfigureServices(s =>
                    {
                        s.AddOcelot();
                        s.AddOcelotConfigEditor<GoogleAuthentication>();
})

change it to

.ConfigureServices(s =>
                    {
                        s.AddOcelot();
                        s.AddOcelotConfigEditor();
})

This will allow you to access the config editor from the localhost of your gateway.

You can change the path you access the editor in appsettings.json or in UseOcelotConfigEditor (ConfigEditorOptions). The default is: cfgedt

**Comment by wangxin5355** [comment]
![image](https://user-images.githubusercontent.com/7795630/51093785-0a0a3680-17e2-11e9-9f92-2e98939c379e.png)
There are some errors here when I call my editor  127.0.0.1:5000/edit
I use Nuget to add OcelotConfigEditor in my project

**Comment by dbarkwell** [comment]
Can you post your Startup.cs?

**Comment by wangxin5355** [comment]
public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
            services.AddOcelotConfigEditor();
            services.AddOcelot().AddConsul();
        }
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }
            app.UseOcelotConfigEditor();
            app.UseOcelot().Wait();
        }
    }

**Comment by dbarkwell** [comment]
I haven't tried it with Consul. I will set it up and see if I can reproduce the exception.

**Comment by dbarkwell** [comment]
I pushed the fix to the repo and updated the nuget package. It should work with Consul now. Let me know if you have any further issues and/or I can close the issue.

**Comment by wangxin5355** [comment]
ok thanks
